from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DecimalField, IntegerField,\
    TextAreaField, SelectField, PasswordField, FloatField, TextField
from wtforms.fields.html5 import EmailField, DateTimeLocalField, DateField, DateTimeField,\
    SearchField
from flask_wtf.file import FileField
from wtforms.widgets import TextArea
from wtforms.validators import Required
from datetime import datetime

class FormCategoria(FlaskForm):
    nombre = StringField("Nombre:", validators=[Required("Tienes que introducir el dato")])
    submit = SubmitField('Enviar')

class FormArticulo(FlaskForm):
    nombre = StringField("Nombre:", validators=[Required("Tienes que introducir el dato")])
    descripcion = TextAreaField("Descripción:", validators=[Required("Tienes que introducir el dato")])
    CategoriaId = SelectField("Nivel:", coerce=int)
    horario = StringField("horario", validators=[Required("Tienes que introducir el dato")])
    fecha = StringField("fecha", validators=[Required("Tienes que introducir el dato")])
    submit = SubmitField('Enviar')

class FormCtofallas(FlaskForm):
    numero = StringField("Numero:")
    falla = StringField("Falla:", validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormSku(FlaskForm):
    sku = IntegerField("Sku:", validators=[Required("Tienes que introducir el dato")])
    producto = StringField("Producto:", validators=[Required("Tienes que introducir el dato")])
    maquina = StringField("Linea", validators=[Required("Tienes que introducir el dato")])
    linea = SelectField(u'Turno')
    kg_min = FloatField("Kg por Min:", validators=[Required("Tienes que introducir el dato")])
    ea_min = FloatField("Unidades por Min:", validators=[Required("Tienes que introducir el dato")])
    descripcion = StringField("Producto:", validators=[Required("Tienes que introducir el dato")])
    buom_descripcion = StringField("Producto:", validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormSINO(FlaskForm):
    si = SubmitField('Si')
    no = SubmitField('No')

class LoginForm(FlaskForm):
    username = StringField('User', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])
    submit = SubmitField('Entrar')

class FormUsuario(FlaskForm):
    username = StringField('Login', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])
    nombre = StringField('Nombre completo')
    email = StringField('Email')
    admin =  SelectField("Admin", choices=[("0", "No"),("1", "Si")], default="No")
    user_fi =  SelectField("FI", choices=[("0", "No"),("1", "Si")], default="No")
    leader_fi =  SelectField("FI", choices=[("0", "No"),("1", "Si")], default="No")
    user_am =  SelectField("AM", choices=[("0", "No"),("1", "Si")], default="No")
    user_auditor =  SelectField("Auditor", choices=[("0", "No"),("1", "Si")], default="No")
    submit = SubmitField('Aceptar')

class FormAuditor_comentario(FlaskForm):
    comentario = StringField('Comentario')
    submit = SubmitField('Aceptar')

class FormEmpleados_cto(FlaskForm):
    NumeroEmpleadoMondelez = StringField('Numero', validators=[Required()])
    NombreEmpleadoMondelez = StringField('Nombre', validators=[Required()])
    submit = SubmitField('Guardar')

class FormChangePassword(FlaskForm):
    password = PasswordField('Password', validators=[Required()])
    submit = SubmitField('Aceptar')

# --------------------------------------------------------------- INCIO CTO'S  -----------------------------------------------------------------#
class FormCto1s_bosch_1(FlaskForm):
    fecha = StringField("Fecha:", validators=[Required("Tienes que introducir el dato")])
    turno = SelectField(u'Turno', choices=[('0', 'Seleccione'),('480', 'Primer Turno'), ('450', 'Segundo Turno'), ('510', 'Tercer Turno')])
    sku = SelectField("Sku")
    maquina = SelectField(u'Maq', choices=[('0', 'Seleccione'),('16.67', 'TG1'), ('16.7', 'TG2')])
    lote = StringField("Lote:", validators=[Required("Tienes que introducir el dato")])
    linea = SelectField(u'Turno', choices=[('Bosch 1s', 'Bosch 1s')])
    nombre_operador = SelectField("Empleado", validators=[Required("Tienes que introducir el dato")])
    nombre_operador_cambios = SelectField("Empleado Cambio")
    codigo_sobre = StringField("Codigo Sobre:")
    tiempo_corrida = StringField("Tiempo Corrida:")
    observaciones = TextAreaField("Observaciones:")
    rework = FloatField("Rework:", default=0)
    scrap = FloatField("Scrap:", default=0)
    lote_bobina = StringField("Lote Bobina:")
    bobina_consumida = FloatField("Bobina Consumida:", default=0)
    total_display = FloatField("Total Display:", default=0)
    ge = FloatField("Ge")
    quality_loss = FloatField("Quality Loss")
    speed_loss = FloatField("Speed Loss")
    min_paro_planeado = IntegerField("Tiempo Min Paro Planeado")
    tiempo_maximo = IntegerField("Tiempo Maximo")
    tiempo_usado = IntegerField("Tiempo Usado")
    tiempo_operativo = FloatField("Tiempo Operativo")
    min_paro_planeado = IntegerField("Min Paro Planeado")
    # INCIO CAMPOS HIDDEN DEFAULT
    area = SelectField(u'Area', choices=[('Slab', 'Slab')])
    linea_cto = SelectField(u'Linea', choices=[('Slab 1s', 'Slab 1s')])
    year = SelectField(u'Linea', choices=[('2021', '2021')])
    planta = SelectField(u'Linea', choices=[('Puebla', 'Puebla')])
    seccion =SelectField(u'Linea', choices=[('Cut&Wrap', 'Cut&Wrap')])
    enviar = SubmitField('Confirmar')

class FormCto1s_bosch_1_fallas(FlaskForm):
    falla = SelectField("Falla:", default=0)
    #perdida =  SelectField("Perdida")
    frec = IntegerField("Frec:", default=0)
    total = FloatField("Total:", default=0)
    falla_2 = SelectField("Total:", default=0)
    frec_2 = IntegerField("Frec 2:", default=0)
    total_2 = FloatField("Total 2:", default=0)
    falla_3 = SelectField("Falla 3:", default=0)
    frec_3 = IntegerField("Frec 3:", default=0)
    total_3 = FloatField("Total 3:", default=0)
    falla_4 = SelectField("Falla 4:", default=0)
    frec_4 = IntegerField("Frec 4:", default=0)
    total_4 = FloatField("Total 4:", default=0)
    falla_5 = SelectField("Falla 5:", default=0)
    frec_5 = IntegerField("Frec 5:", default=0)
    total_5 = FloatField("Total 5:", default=0)
    falla_6 = SelectField("Falla 6:", default=0)
    frec_6 = IntegerField("Frec 6:", default=0)
    total_6 = FloatField("Total 6:", default=0)
    falla_7 = SelectField("Falla 7:", default=0)
    frec_7 = IntegerField("Frec 7:", default=0)
    total_7 = FloatField("Total 7:", default=0)
    falla_8 = SelectField("Falla 8:", default=0)
    frec_8 = IntegerField("Frec 8:", default=0)
    total_8 = FloatField("Total 8:", default=0)
    falla_9 = SelectField("Falla 9:", default=0)
    frec_9 = IntegerField("Frec 9:", default=0)
    total_9 = FloatField("Total 9:", default=0)
    falla_10 = SelectField("Falla 10:", default=0)
    frec_10 = IntegerField("Frec 10:", default=0)
    total_10 = FloatField("Total 10:", default=0)
    falla_11 = SelectField("Falla 11:", default=0)
    frec_11 = IntegerField("Frec 11:", default=0)
    total_11 = FloatField("Total 11:", default=0)
    falla_12 = SelectField("Falla 12:", default=0)
    frec_12 = IntegerField("Frec 12:", default=0)
    total_12 = FloatField("Total 12:", default=0)
    falla_13 = SelectField("Falla 13:", default=0)
    frec_13 = IntegerField("Frec 13:", default=0)
    total_13 = FloatField("Total 13:", default=0)
    falla_14 = SelectField("Falla 14:", default=0)
    frec_14 = IntegerField("Frec 14:", default=0)
    total_14 = FloatField("Total 14:", default=0)
    falla_15 = SelectField("Falla 15:", default=0)
    frec_15 = IntegerField("Frec 15:", default=0)
    total_15 = FloatField("Total 15:", default=0)

class FormCto1s_bosch_2(FlaskForm):
    fecha = StringField("Fecha:", validators=[Required("Tienes que introducir el dato")])
    turno = SelectField(u'Turno', choices=[('0', 'Seleccione'),('480', 'Primer Turno'), ('450', 'Segundo Turno'), ('510', 'Tercer Turno')])
    sku = SelectField("Sku")
    maquina = SelectField(u'Maq', choices=[('0', 'Seleccione'),('15.15', 'TG1'), ('15.2', 'TG2')])
    #maquina = SelectField("Maquina")
    lote = StringField("Lote:", validators=[Required("Tienes que introducir el dato")])
    linea = SelectField(u'Turno', choices=[('Bosch 2', 'Bosch 2')])
    #nombre_operador = StringField("Nombre Operador:", validators=[Required("Tienes que introducir el dato")])
    nombre_operador = SelectField("Empleado", validators=[Required("Tienes que introducir el dato")])
    #nombre_operador_cambios = StringField("Nombre Operador:")
    nombre_operador_cambios = SelectField("Empleado Cambio")
    codigo_sobre = StringField("Codigo Sobre:")
    tiempo_corrida = StringField("Tiempo Corrida:")
    observaciones = TextAreaField("Observaciones:")
    rework = FloatField("Rework:", default=0)
    scrap = FloatField("Scrap:", default=0)
    lote_bobina = StringField("Lote Bobina:")
    bobina_consumida = FloatField("Bobina Consumida:", default=0)
    total_display = FloatField("Total Display:", default=0)
    ge = FloatField("Ge")
    quality_loss = FloatField("Quality Loss")
    speed_loss = FloatField("Speed Loss")
    min_paro_planeado = IntegerField("Tiempo Min Paro Planeado")
    tiempo_maximo = IntegerField("Tiempo Maximo")
    tiempo_usado = IntegerField("Tiempo Usado")
    tiempo_operativo = FloatField("Tiempo Operativo")
    min_paro_planeado = IntegerField("Min Paro Planeado")
    # INCIO CAMPOS HIDDEN DEFAULT
    area = SelectField(u'Area', choices=[('Slab', 'Slab')])
    linea_cto = SelectField(u'Linea', choices=[('Slab 1s', 'Slab 1s')])
    year = SelectField(u'Linea', choices=[('2021', '2021')])
    planta = SelectField(u'Linea', choices=[('Puebla', 'Puebla')])
    seccion =SelectField(u'Linea', choices=[('Cut&Wrap', 'Cut&Wrap')])
    # FIN CAMPOS HIDDEN DEFAULT
    falla = SelectField("Falla:", default=0)
    #perdida =  SelectField("Perdida")
    frec = IntegerField("Frec:", default=0)
    total = FloatField("Total:", default=0)
    falla_2 = SelectField("Total:", default=0)
    frec_2 = IntegerField("Frec 2:", default=0)
    total_2 = FloatField("Total 2:", default=0)
    falla_3 = SelectField("Falla 3:", default=0)
    frec_3 = IntegerField("Frec 3:", default=0)
    total_3 = FloatField("Total 3:", default=0)
    falla_4 = SelectField("Falla 4:", default=0)
    frec_4 = IntegerField("Frec 4:", default=0)
    total_4 = FloatField("Total 4:", default=0)
    falla_5 = SelectField("Falla 5:", default=0)
    frec_5 = IntegerField("Frec 5:", default=0)
    total_5 = FloatField("Total 5:", default=0)
    falla_6 = SelectField("Falla 6:", default=0)
    frec_6 = IntegerField("Frec 6:", default=0)
    total_6 = FloatField("Total 6:", default=0)
    falla_7 = SelectField("Falla 7:", default=0)
    frec_7 = IntegerField("Frec 7:", default=0)
    total_7 = FloatField("Total 7:", default=0)
    falla_8 = SelectField("Falla 8:", default=0)
    frec_8 = IntegerField("Frec 8:", default=0)
    total_8 = FloatField("Total 8:", default=0)
    falla_9 = SelectField("Falla 9:", default=0)
    frec_9 = IntegerField("Frec 9:", default=0)
    total_9 = FloatField("Total 9:", default=0)
    falla_10 = SelectField("Falla 10:", default=0)
    frec_10 = IntegerField("Frec 10:", default=0)
    total_10 = FloatField("Total 10:", default=0)
    falla_11 = SelectField("Falla 11:", default=0)
    frec_11 = IntegerField("Frec 11:", default=0)
    total_11 = FloatField("Total 11:", default=0)
    falla_12 = SelectField("Falla 12:", default=0)
    frec_12 = IntegerField("Frec 12:", default=0)
    total_12 = FloatField("Total 12:", default=0)
    falla_13 = SelectField("Falla 13:", default=0)
    frec_13 = IntegerField("Frec 13:", default=0)
    total_13 = FloatField("Total 13:", default=0)
    falla_14 = SelectField("Falla 14:", default=0)
    frec_14 = IntegerField("Frec 14:", default=0)
    total_14 = FloatField("Total 14:", default=0)
    falla_15 = SelectField("Falla 15:", default=0)
    frec_15 = IntegerField("Frec 15:", default=0)
    total_15 = FloatField("Total 15:", default=0)
    enviar = SubmitField('Confirmar')

class FormCto6s_prototipo_l1(FlaskForm):
    fecha = StringField("Fecha:", validators=[Required("Tienes que introducir el dato")])
    turno = SelectField(u'Turno', choices=[('0', 'Seleccione'),('480', 'Primer Turno'), ('450', 'Segundo Turno'), ('510', 'Tercer Turno')])
    sku = SelectField("Sku")
    maquina = SelectField(u'Maq', choices=[('0', 'Seleccione'),('17.7', 'L1')])
    #maquina = SelectField("Maquina")
    lote = StringField("Lote:", validators=[Required("Tienes que introducir el dato")])
    linea = SelectField(u'Turno', choices=[('Linea 1', 'Linea 1')])
    nombre_operador = SelectField("Empleado", validators=[Required("Tienes que introducir el dato")])
    nombre_operador_cambios = SelectField("Empleado Cambio")
    codigo_sobre = StringField("Codigo Sobre:")
    tiempo_corrida = StringField("Tiempo Corrida:")
    observaciones = TextAreaField("Observaciones:")
    rework = FloatField("Rework:", default=0)
    scrap = FloatField("Scrap:", default=0)
    lote_bobina = StringField("Lote Bobina:")
    bobina_consumida = FloatField("Bobina Consumida:", default=0)
    total_display = FloatField("Total Display:", default=0)
    ge = FloatField("Ge")
    quality_loss = FloatField("Quality Loss")
    speed_loss = FloatField("Speed Loss")
    min_paro_planeado = IntegerField("Tiempo Min Paro Planeado")
    tiempo_maximo = IntegerField("Tiempo Maximo")
    tiempo_usado = IntegerField("Tiempo Usado")
    tiempo_operativo = FloatField("Tiempo Operativo")
    min_paro_planeado = IntegerField("Min Paro Planeado")
    # INCIO CAMPOS HIDDEN DEFAULT
    area = SelectField(u'Area', choices=[('Slab', 'Slab')])
    linea_cto = SelectField(u'Linea', choices=[('Slab 6s', 'Slab 6s')])
    year = SelectField(u'Linea', choices=[('2021', '2021')])
    planta = SelectField(u'Linea', choices=[('Puebla', 'Puebla')])
    seccion =SelectField(u'Linea', choices=[('Cut&Wrap', 'Cut&Wrap')])
    # FIN CAMPOS HIDDEN DEFAULT
    falla = SelectField("Frec:", default=0)
    frec = IntegerField("Frec:", default=0)
    total = FloatField("Total:", default=0)
    falla_2 = SelectField("Total:", default=0)
    frec_2 = IntegerField("Frec 2:", default=0)
    total_2 = FloatField("Total 2:", default=0)
    falla_3 = SelectField("Falla 3:", default=0)
    frec_3 = IntegerField("Frec 3:", default=0)
    total_3 = FloatField("Total 3:", default=0)
    falla_4 = SelectField("Falla 4:", default=0)
    frec_4 = IntegerField("Frec 4:", default=0)
    total_4 = FloatField("Total 4:", default=0)
    falla_5 = SelectField("Falla 5:", default=0)
    frec_5 = IntegerField("Frec 5:", default=0)
    total_5 = FloatField("Total 5:", default=0)
    falla_6 = SelectField("Falla 6:", default=0)
    frec_6 = IntegerField("Frec 6:", default=0)
    total_6 = FloatField("Total 6:", default=0)
    falla_7 = SelectField("Falla 7:", default=0)
    frec_7 = IntegerField("Frec 7:", default=0)
    total_7 = FloatField("Total 7:", default=0)
    falla_8 = SelectField("Falla 8:", default=0)
    frec_8 = IntegerField("Frec 8:", default=0)
    total_8 = FloatField("Total 8:", default=0)
    falla_9 = SelectField("Falla 9:", default=0)
    frec_9 = IntegerField("Frec 9:", default=0)
    total_9 = FloatField("Total 9:", default=0)
    falla_10 = SelectField("Falla 10:", default=0)
    frec_10 = IntegerField("Frec 10:", default=0)
    total_10 = FloatField("Total 10:", default=0)
    falla_11 = SelectField("Falla 11:", default=0)
    frec_11 = IntegerField("Frec 11:", default=0)
    total_11 = FloatField("Total 11:", default=0)
    falla_12 = SelectField("Falla 12:", default=0)
    frec_12 = IntegerField("Frec 12:", default=0)
    total_12 = FloatField("Total 12:", default=0)
    falla_13 = SelectField("Falla 13:", default=0)
    frec_13 = IntegerField("Frec 13:", default=0)
    total_13 = FloatField("Total 13:", default=0)
    falla_14 = SelectField("Falla 14:", default=0)
    frec_14 = IntegerField("Frec 14:", default=0)
    total_14 = FloatField("Total 14:", default=0)
    falla_15 = SelectField("Falla 15:", default=0)
    frec_15 = IntegerField("Frec 15:", default=0)
    total_15 = FloatField("Total 15:", default=0)
    enviar = SubmitField('Confirmar')

class FormCto6s_prototipo_l2(FlaskForm):
    fecha = StringField("Fecha:", validators=[Required("Tienes que introducir el dato")])
    turno = SelectField(u'Turno', choices=[('0', 'Seleccione'),('480', 'Primer Turno'), ('450', 'Segundo Turno'), ('510', 'Tercer Turno')])
    sku = SelectField("Sku")
    maquina = SelectField(u'Maq', choices=[('0', 'Seleccione'),('17.7', 'L2')])
    #maquina = SelectField("Maquina")
    lote = StringField("Lote:", validators=[Required("Tienes que introducir el dato")])
    linea = SelectField(u'Turno', choices=[('Linea 2', 'Linea 2')])
    #nombre_operador = StringField("Nombre Operador:", validators=[Required("Tienes que introducir el dato")])
    nombre_operador = SelectField("Empleado", validators=[Required("Tienes que introducir el dato")])
    #nombre_operador_cambios = StringField("Nombre Operador:")
    nombre_operador_cambios = SelectField("Empleado Cambio")
    codigo_sobre = StringField("Codigo Sobre:")
    tiempo_corrida = StringField("Tiempo Corrida:")
    observaciones = TextAreaField("Observaciones:")
    rework = FloatField("Rework:", default=0)
    scrap = FloatField("Scrap:", default=0)
    lote_bobina = StringField("Lote Bobina:")
    bobina_consumida = FloatField("Bobina Consumida:", default=0)
    total_display = FloatField("Total Display:", default=0)
    ge = FloatField("Ge")
    quality_loss = FloatField("Quality Loss")
    speed_loss = FloatField("Speed Loss")
    min_paro_planeado = IntegerField("Tiempo Min Paro Planeado")
    tiempo_maximo = IntegerField("Tiempo Maximo")
    tiempo_usado = IntegerField("Tiempo Usado")
    tiempo_operativo = FloatField("Tiempo Operativo")
    min_paro_planeado = IntegerField("Min Paro Planeado")
    # INCIO CAMPOS HIDDEN DEFAULT
    area = SelectField(u'Area', choices=[('Slab', 'Slab')])
    linea_cto = SelectField(u'Linea', choices=[('Slab 6s', 'Slab 6s')])
    year = SelectField(u'Linea', choices=[('2021', '2021')])
    planta = SelectField(u'Linea', choices=[('Puebla', 'Puebla')])
    seccion =SelectField(u'Linea', choices=[('Cut&Wrap', 'Cut&Wrap')])
    # FIN CAMPOS HIDDEN DEFAULT
    falla = SelectField("Frec:", default=0)
    frec = IntegerField("Frec:", default=0)
    total = FloatField("Total:", default=0)
    falla_2 = SelectField("Total:", default=0)
    frec_2 = IntegerField("Frec 2:", default=0)
    total_2 = FloatField("Total 2:", default=0)
    falla_3 = SelectField("Falla 3:", default=0)
    frec_3 = IntegerField("Frec 3:", default=0)
    total_3 = FloatField("Total 3:", default=0)
    falla_4 = SelectField("Falla 4:", default=0)
    frec_4 = IntegerField("Frec 4:", default=0)
    total_4 = FloatField("Total 4:", default=0)
    falla_5 = SelectField("Falla 5:", default=0)
    frec_5 = IntegerField("Frec 5:", default=0)
    total_5 = FloatField("Total 5:", default=0)
    falla_6 = SelectField("Falla 6:", default=0)
    frec_6 = IntegerField("Frec 6:", default=0)
    total_6 = FloatField("Total 6:", default=0)
    falla_7 = SelectField("Falla 7:", default=0)
    frec_7 = IntegerField("Frec 7:", default=0)
    total_7 = FloatField("Total 7:", default=0)
    falla_8 = SelectField("Falla 8:", default=0)
    frec_8 = IntegerField("Frec 8:", default=0)
    total_8 = FloatField("Total 8:", default=0)
    falla_9 = SelectField("Falla 9:", default=0)
    frec_9 = IntegerField("Frec 9:", default=0)
    total_9 = FloatField("Total 9:", default=0)
    falla_10 = SelectField("Falla 10:", default=0)
    frec_10 = IntegerField("Frec 10:", default=0)
    total_10 = FloatField("Total 10:", default=0)
    falla_11 = SelectField("Falla 11:", default=0)
    frec_11 = IntegerField("Frec 11:", default=0)
    total_11 = FloatField("Total 11:", default=0)
    falla_12 = SelectField("Falla 12:", default=0)
    frec_12 = IntegerField("Frec 12:", default=0)
    total_12 = FloatField("Total 12:", default=0)
    falla_13 = SelectField("Falla 13:", default=0)
    frec_13 = IntegerField("Frec 13:", default=0)
    total_13 = FloatField("Total 13:", default=0)
    falla_14 = SelectField("Falla 14:", default=0)
    frec_14 = IntegerField("Frec 14:", default=0)
    total_14 = FloatField("Total 14:", default=0)
    falla_15 = SelectField("Falla 15:", default=0)
    frec_15 = IntegerField("Frec 15:", default=0)
    total_15 = FloatField("Total 15:", default=0)
    enviar = SubmitField('Confirmar')

class FormCto6s_prototipo_l3(FlaskForm):
    fecha = StringField("Fecha:", validators=[Required("Tienes que introducir el dato")])
    turno = SelectField(u'Turno', choices=[('0', 'Seleccione'),('480', 'Primer Turno'), ('450', 'Segundo Turno'), ('510', 'Tercer Turno')])
    sku = SelectField("Sku")
    maquina = SelectField(u'Maq', choices=[('0', 'Seleccione'),('11.6', 'L3')])
    #maquina = SelectField("Maquina")
    lote = StringField("Lote:", validators=[Required("Tienes que introducir el dato")])
    linea = SelectField(u'Turno', choices=[('Linea 3', 'Linea 3')])
    #nombre_operador = StringField("Nombre Operador:", validators=[Required("Tienes que introducir el dato")])
    nombre_operador = SelectField("Empleado", validators=[Required("Tienes que introducir el dato")])
    #nombre_operador_cambios = StringField("Nombre Operador:")
    nombre_operador_cambios = SelectField("Empleado Cambio")
    codigo_sobre = StringField("Codigo Sobre:")
    tiempo_corrida = StringField("Tiempo Corrida:")
    observaciones = TextAreaField("Observaciones:")
    rework = FloatField("Rework:", default=0)
    scrap = FloatField("Scrap:", default=0)
    lote_bobina = StringField("Lote Bobina:")
    bobina_consumida = FloatField("Bobina Consumida:", default=0)
    total_display = FloatField("Total Display:", default=0)
    ge = FloatField("Ge")
    quality_loss = FloatField("Quality Loss")
    speed_loss = FloatField("Speed Loss")
    min_paro_planeado = IntegerField("Tiempo Min Paro Planeado")
    tiempo_maximo = IntegerField("Tiempo Maximo")
    tiempo_usado = IntegerField("Tiempo Usado")
    tiempo_operativo = FloatField("Tiempo Operativo")
    min_paro_planeado = IntegerField("Min Paro Planeado")
    # INCIO CAMPOS HIDDEN DEFAULT
    area = SelectField(u'Area', choices=[('Slab', 'Slab')])
    linea_cto = SelectField(u'Linea', choices=[('Slab 6s', 'Slab 6s')])
    year = SelectField(u'Linea', choices=[('2021', '2021')])
    planta = SelectField(u'Linea', choices=[('Puebla', 'Puebla')])
    seccion =SelectField(u'Linea', choices=[('Cut&Wrap', 'Cut&Wrap')])
    # FIN CAMPOS HIDDEN DEFAULT
    falla = SelectField("Frec:", default=0)
    frec = IntegerField("Frec:", default=0)
    total = FloatField("Total:", default=0)
    falla_2 = SelectField("Total:", default=0)
    frec_2 = IntegerField("Frec 2:", default=0)
    total_2 = FloatField("Total 2:", default=0)
    falla_3 = SelectField("Falla 3:", default=0)
    frec_3 = IntegerField("Frec 3:", default=0)
    total_3 = FloatField("Total 3:", default=0)
    falla_4 = SelectField("Falla 4:", default=0)
    frec_4 = IntegerField("Frec 4:", default=0)
    total_4 = FloatField("Total 4:", default=0)
    falla_5 = SelectField("Falla 5:", default=0)
    frec_5 = IntegerField("Frec 5:", default=0)
    total_5 = FloatField("Total 5:", default=0)
    falla_6 = SelectField("Falla 6:", default=0)
    frec_6 = IntegerField("Frec 6:", default=0)
    total_6 = FloatField("Total 6:", default=0)
    falla_7 = SelectField("Falla 7:", default=0)
    frec_7 = IntegerField("Frec 7:", default=0)
    total_7 = FloatField("Total 7:", default=0)
    falla_8 = SelectField("Falla 8:", default=0)
    frec_8 = IntegerField("Frec 8:", default=0)
    total_8 = FloatField("Total 8:", default=0)
    falla_9 = SelectField("Falla 9:", default=0)
    frec_9 = IntegerField("Frec 9:", default=0)
    total_9 = FloatField("Total 9:", default=0)
    falla_10 = SelectField("Falla 10:", default=0)
    frec_10 = IntegerField("Frec 10:", default=0)
    total_10 = FloatField("Total 10:", default=0)
    falla_11 = SelectField("Falla 11:", default=0)
    frec_11 = IntegerField("Frec 11:", default=0)
    total_11 = FloatField("Total 11:", default=0)
    falla_12 = SelectField("Falla 12:", default=0)
    frec_12 = IntegerField("Frec 12:", default=0)
    total_12 = FloatField("Total 12:", default=0)
    falla_13 = SelectField("Falla 13:", default=0)
    frec_13 = IntegerField("Frec 13:", default=0)
    total_13 = FloatField("Total 13:", default=0)
    falla_14 = SelectField("Falla 14:", default=0)
    frec_14 = IntegerField("Frec 14:", default=0)
    total_14 = FloatField("Total 14:", default=0)
    falla_15 = SelectField("Falla 15:", default=0)
    frec_15 = IntegerField("Frec 15:", default=0)
    total_15 = FloatField("Total 15:", default=0)
    enviar = SubmitField('Confirmar')

class FormCto6s_prototipo_l4(FlaskForm):
    fecha = StringField("Fecha:", validators=[Required("Tienes que introducir el dato")])
    turno = SelectField(u'Turno', choices=[('0', 'Seleccione'),('480', 'Primer Turno'), ('450', 'Segundo Turno'), ('510', 'Tercer Turno')])
    sku = SelectField("Sku")
    maquina = SelectField(u'Maq', choices=[('0', 'Seleccione'),('11.6', 'L4')])
    #maquina = SelectField("Maquina")
    lote = StringField("Lote:", validators=[Required("Tienes que introducir el dato")])
    linea = SelectField(u'Turno', choices=[('Linea 4', 'Linea 4')])
    #nombre_operador = StringField("Nombre Operador:", validators=[Required("Tienes que introducir el dato")])
    nombre_operador = SelectField("Empleado", validators=[Required("Tienes que introducir el dato")])
    #nombre_operador_cambios = StringField("Nombre Operador:")
    nombre_operador_cambios = SelectField("Empleado Cambio")
    codigo_sobre = StringField("Codigo Sobre:")
    tiempo_corrida = StringField("Tiempo Corrida:")
    observaciones = TextAreaField("Observaciones:")
    rework = FloatField("Rework:", default=0)
    scrap = FloatField("Scrap:", default=0)
    lote_bobina = StringField("Lote Bobina:")
    bobina_consumida = FloatField("Bobina Consumida:", default=0)
    total_display = FloatField("Total Display:", default=0)
    ge = FloatField("Ge")
    quality_loss = FloatField("Quality Loss")
    speed_loss = FloatField("Speed Loss")
    min_paro_planeado = IntegerField("Tiempo Min Paro Planeado")
    tiempo_maximo = IntegerField("Tiempo Maximo")
    tiempo_usado = IntegerField("Tiempo Usado")
    tiempo_operativo = FloatField("Tiempo Operativo")
    min_paro_planeado = IntegerField("Min Paro Planeado")
    # INCIO CAMPOS HIDDEN DEFAULT
    area = SelectField(u'Area', choices=[('Slab', 'Slab')])
    linea_cto = SelectField(u'Linea', choices=[('Slab 6s', 'Slab 6s')])
    year = SelectField(u'Linea', choices=[('2021', '2021')])
    planta = SelectField(u'Linea', choices=[('Puebla', 'Puebla')])
    seccion =SelectField(u'Linea', choices=[('Cut&Wrap', 'Cut&Wrap')])
    # FIN CAMPOS HIDDEN DEFAULT
    falla = SelectField("Frec:", default=0)
    frec = IntegerField("Frec:", default=0)
    total = FloatField("Total:", default=0)
    falla_2 = SelectField("Total:", default=0)
    frec_2 = IntegerField("Frec 2:", default=0)
    total_2 = FloatField("Total 2:", default=0)
    falla_3 = SelectField("Falla 3:", default=0)
    frec_3 = IntegerField("Frec 3:", default=0)
    total_3 = FloatField("Total 3:", default=0)
    falla_4 = SelectField("Falla 4:", default=0)
    frec_4 = IntegerField("Frec 4:", default=0)
    total_4 = FloatField("Total 4:", default=0)
    falla_5 = SelectField("Falla 5:", default=0)
    frec_5 = IntegerField("Frec 5:", default=0)
    total_5 = FloatField("Total 5:", default=0)
    falla_6 = SelectField("Falla 6:", default=0)
    frec_6 = IntegerField("Frec 6:", default=0)
    total_6 = FloatField("Total 6:", default=0)
    falla_7 = SelectField("Falla 7:", default=0)
    frec_7 = IntegerField("Frec 7:", default=0)
    total_7 = FloatField("Total 7:", default=0)
    falla_8 = SelectField("Falla 8:", default=0)
    frec_8 = IntegerField("Frec 8:", default=0)
    total_8 = FloatField("Total 8:", default=0)
    falla_9 = SelectField("Falla 9:", default=0)
    frec_9 = IntegerField("Frec 9:", default=0)
    total_9 = FloatField("Total 9:", default=0)
    falla_10 = SelectField("Falla 10:", default=0)
    frec_10 = IntegerField("Frec 10:", default=0)
    total_10 = FloatField("Total 10:", default=0)
    falla_11 = SelectField("Falla 11:", default=0)
    frec_11 = IntegerField("Frec 11:", default=0)
    total_11 = FloatField("Total 11:", default=0)
    falla_12 = SelectField("Falla 12:", default=0)
    frec_12 = IntegerField("Frec 12:", default=0)
    total_12 = FloatField("Total 12:", default=0)
    falla_13 = SelectField("Falla 13:", default=0)
    frec_13 = IntegerField("Frec 13:", default=0)
    total_13 = FloatField("Total 13:", default=0)
    falla_14 = SelectField("Falla 14:", default=0)
    frec_14 = IntegerField("Frec 14:", default=0)
    total_14 = FloatField("Total 14:", default=0)
    falla_15 = SelectField("Falla 15:", default=0)
    frec_15 = IntegerField("Frec 15:", default=0)
    total_15 = FloatField("Total 15:", default=0)
    enviar = SubmitField('Confirmar')

# --------------------------------------------------------------- FIN CTO'S  -------------------------------------------------------------------#
