from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DecimalField, IntegerField,\
    TextAreaField, SelectField, PasswordField, HiddenField, FloatField
from wtforms.fields.html5 import EmailField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms.widgets import TextArea
from wtforms.validators import Required, NumberRange

class FormMission_fi(FlaskForm):
    titulo = StringField('Titulo')
    photo = FileField('selecciona imagen:',validators=[FileRequired()])
    submit = SubmitField('Guardar')

class FormOrganigrama_fi(FlaskForm):
    titulo = StringField("Titulo", validators=[Required("Tienes que introducir el dato")])
    nombre = StringField("Nombre", validators=[Required("Tienes que introducir el dato")])
    rol = StringField("Rol", validators=[Required("Tienes que introducir el dato")])
    photo = FileField('selecciona imagen:')
    submit = SubmitField('Guardar')

class FormCbn_fi(FlaskForm):
    elemento_cbn = StringField("Elemento", validators=[Required("Tienes que introducir el dato")])
    temas = StringField("Temas", validators=[Required("Tienes que introducir el dato")])
    capacidad = StringField("Capacidad", validators=[Required("Tienes que introducir el dato")])
    medidas = StringField("Medidas")
    submit = SubmitField('Enviar')

class FormPilar_swot_fi(FlaskForm):
    workprocess = StringField("Elemento", validators=[Required("Tienes que introducir el dato")])
    dueño = StringField("Temas", validators=[Required("Tienes que introducir el dato")])
    back_up = StringField("Capacidad", validators=[Required("Tienes que introducir el dato")])
    submit = SubmitField('Enviar')

class FormMasterplan_fi(FlaskForm):
    action_plan = StringField("Action Plan")
    #owner = StringField("Owner", validators=[Required("Tienes que introducir el dato")])
    owner = SelectField(u'Resp', choices=[('-', 'No Asignado'), ('B.S', 'Benjamin Sanchez'), ('K.H', 'Kimberly Herrera'), ('N.L', 'Naville Limón'), ('R.H', 'Rafael Hernández'), ('G.F', 'Germán Fernández')])
    levl = SelectField("Estado", choices=[('Realizado', 'Realizado'), ('Plandeado', 'Planeado')])
    #q1_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q2_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q3_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q4_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q1_2021 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q2_2021 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q3_2021 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q4_2021 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q1_2022 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q2_2022 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q3_2022 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    #q4_2022 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    # 2020
    ene_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    feb_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    mar_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    abr_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    may_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    jun_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    jul_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    ago_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    sep_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    oct_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    nov_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    dic_2020 = SelectField(u'2020', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    # 2021
    ene_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    feb_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    mar_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    abr_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    may_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    jun_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    jul_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    ago_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    sep_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    oct_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    nov_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    dic_2021 = SelectField(u'2021', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    # 2022
    ene_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    feb_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    mar_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    abr_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    may_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    jun_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    jul_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    ago_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    sep_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    oct_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    nov_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    dic_2022 = SelectField(u'2022', choices=[('text-white', 'No Asignado'), ('text-success', 'Concluido'), ('text-yellow', 'En Proceso'), ('text-red', 'Atrasado'), ('text-blue', 'Planeado')])
    enviar = SubmitField('Enviar')

class FormTeamcharter_fi(FlaskForm):
    propositos = StringField("Propositos", widget=TextArea(), validators=[Required("Tienes que introducir el dato")])
    #resultados = StringField("Resultados", validators=[Required("Tienes que introducir el dato")])
    resultados = StringField("Resultados", widget=TextArea(), validators=[Required("Tienes que introducir el dato")])
    estrategia = StringField("Estrategia", widget=TextArea(), validators=[Required("Tienes que introducir el dato")])
    principios = StringField("Principios", widget=TextArea(), validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormTeamcharter_comite_fi(FlaskForm):
    miembro = StringField("Miembro", validators=[Required("Tienes que introducir el dato")])
    area = SelectField(u'Area', choices=[('FI', 'Focus Improvement')])
    rol = StringField("Rol", validators=[Required("Tienes que introducir el dato")])
    sistema = StringField("Sistema", validators=[Required("Tienes que introducir el dato")])
    firma = StringField("firma", validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormScorecard_fi(FlaskForm):
    categoria = SelectField("Propositos", choices=[('-', 'Select'), ('KPI', 'KPI'), ('KAI', 'KAI')])
    nombre = StringField("Propositos", validators=[Required("Tienes que introducir el dato")])
    formula = StringField("Propositos", validators=[Required("Tienes que introducir el dato")])
    criterio_de_exito = StringField("Propositos", validators=[Required("Tienes que introducir el dato")])
    unidades_medida = StringField("Propositos", validators=[Required("Tienes que introducir el dato")])
    tg = StringField("Tg", validators=[Required("Tienes que introducir el dato")])
    fye = StringField("Fye", validators=[Required("Tienes que introducir el dato")])
    ene = StringField("Enero")
    feb = StringField("Febrero")
    mar = StringField("Marzo")
    abr = StringField("Abril")
    may = StringField("Mayo")
    jun = StringField("Junio")
    jul = StringField("Julio")
    ago = StringField("Agosto")
    sep = StringField("Septiembre")
    oct = StringField("Octubre")
    nov = StringField("Noviembre")
    dic = StringField("Diciembre")
    enviar = SubmitField('Enviar')

class FormOnepager_fi(FlaskForm):
    assessment_date = StringField("Assessment Date", validators=[Required("Tienes que introducir el dato")])
    pilar_leader = StringField("Pilar Leader", validators=[Required("Tienes que introducir el dato")])
    training_status = StringField("Training Status")
    qualification_date = StringField("Qualification Date", validators=[Required("Tienes que introducir el dato")])
    qualified_by = StringField("Qualified By", validators=[Required("Tienes que introducir el dato")])
    assessment_score = StringField("Assessment Score")
    ready_to_approve = StringField("Ready to Approve")
    tpm_coach = StringField("TPM Coach")
    # Segundo
    propositos_pilar = StringField("Propositos Pilar")
    resultados_esperados = StringField("Resultados Esperados")
    # Tercero
    metrics = StringField("Metrics")
    baseline = StringField("BaseLine")
    last_year = StringField("Last Year")
    target_year = StringField("Target Year")
    actual_result = StringField("Actual Result")
    improvement_base = StringField("Improvement Base")
    jipm_criteria = StringField("Jimp Criteria")
    # Cuarto
    standar_work = StringField("Standar Work")
    system_owner = StringField("System Owner")
    swp_documented = StringField("Swp Document")
    health_check = StringField("Health Check")
    system_tracks = StringField("System Tracks")
    system_range = StringField("System Range")
    # Quinto
    gaps = StringField("Gaps")
    addressed_by = StringField("Addressed By")
    estimated_completion_date = StringField("Estimated Completion")
    enviar = SubmitField('Enviar')

class FormPilarlossmap_fi(FlaskForm):
    tema = StringField('Tema', validators=[Required("Tienes que introducir el dato")])
    responsable = StringField('Responsable', validators=[Required("Tienes que introducir el dato")])
    objetivo = StringField('Objetivo', validators=[Required("Tienes que introducir el dato")])
    estadoactual = SelectField(u'Estatus', choices=[('-', 'No Asignado'), ('Planeado', 'Planeado'), ('En Proceso', 'En Proceso'), ('Concluido', 'Concluido')])
    estadofuturo = SelectField(u'Estatus', choices=[('-', 'No Asignado'), ('Planeado', 'Planeado'), ('En Proceso', 'En Proceso'), ('Concluido', 'Concluido')])
    planesdeaccion = StringField('Plan de Accion', validators=[Required("Tienes que introducir el dato")])
    fecha = StringField('Fecha')
    enviar = SubmitField('Enviar')

class FormTeamcapability_fi(FlaskForm):
    nombre = StringField("Nombre:", validators=[Required("Tienes que introducir el dato")])
    objetivo = IntegerField("Objetivo", default=100)
    acreditacion = FloatField("Acreditacion", default=00)
    calificacion = IntegerField("Calificacion", default=00)
    submit = SubmitField('Enviar')

class FormTeam_capability_fi(FlaskForm):
    basic_1 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    basic_2 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    basic_3 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    basic_4 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    basic_5 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_1 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_2 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_3 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_4 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_5 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_1 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_2 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_3 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_4 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_5 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_6 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_7 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_1 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_2 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_3 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_4 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_5 = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    # Seccion del leader
    basic_1_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    basic_2_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    basic_3_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    basic_4_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    basic_5_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_1_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_2_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_3_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_4_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    intelligence_5_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_1_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_2_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_3_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_4_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_5_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_6_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    eradication_7_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_1_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_2_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_3_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_4_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    prevention_5_leader = SelectField(u'cal', choices=[('0', 'No Asignado'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')])
    #submit = SubmitField('Enviar')

class FormGapanalisis_fi_1(FlaskForm):
    objetivo_analisis = StringField("Objetivo Analisis", validators=[Required("Tienes que introducir el dato")])
    fecha = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    causa_raices = StringField("Causa Raices", validators=[Required("Tienes que introducir el dato")])
    plan_accion = StringField("Plan Accion", validators=[Required("Tienes que introducir el dato")])
    responsable = StringField("Responsable", validators=[Required("Tienes que introducir el dato")])
    fecha_1 = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    status = StringField("Status", validators=[Required("Tienes que introducir el dato")])
    explique = TextAreaField("Explique:", validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_1_efecto(FlaskForm):
    efecto_1 = StringField("efecto_1", validators=[Required("Tienes que introducir el dato")])
    efecto_2 = StringField("efecto_2", validators=[Required("Tienes que introducir el dato")])
    efecto_3 = StringField("efecto_3", validators=[Required("Tienes que introducir el dato")])
    efecto_4 = StringField("efecto_4")
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_2(FlaskForm):
    objetivo_analisis = StringField("Objetivo Analisis", validators=[Required("Tienes que introducir el dato")])
    fecha = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    causa_raices = StringField("Causa Raices", validators=[Required("Tienes que introducir el dato")])
    plan_accion = StringField("Plan Accion", validators=[Required("Tienes que introducir el dato")])
    responsable = StringField("Responsable", validators=[Required("Tienes que introducir el dato")])
    fecha_1 = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    status = StringField("Status", validators=[Required("Tienes que introducir el dato")])
    explique = TextAreaField("Explique:", validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_2_efecto(FlaskForm):
    efecto_1 = StringField("efecto_1", validators=[Required("Tienes que introducir el dato")])
    efecto_2 = StringField("efecto_2", validators=[Required("Tienes que introducir el dato")])
    efecto_3 = StringField("efecto_3", validators=[Required("Tienes que introducir el dato")])
    efecto_4 = StringField("efecto_4")
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_3(FlaskForm):
    objetivo_analisis = StringField("Objetivo Analisis", validators=[Required("Tienes que introducir el dato")])
    fecha = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    causa_raices = StringField("Causa Raices", validators=[Required("Tienes que introducir el dato")])
    plan_accion = StringField("Plan Accion", validators=[Required("Tienes que introducir el dato")])
    responsable = StringField("Responsable", validators=[Required("Tienes que introducir el dato")])
    fecha_1 = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    status = StringField("Status", validators=[Required("Tienes que introducir el dato")])
    explique = TextAreaField("Explique:", validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_3_efecto(FlaskForm):
    efecto_1 = StringField("efecto_1", validators=[Required("Tienes que introducir el dato")])
    efecto_2 = StringField("efecto_2", validators=[Required("Tienes que introducir el dato")])
    efecto_3 = StringField("efecto_3", validators=[Required("Tienes que introducir el dato")])
    efecto_4 = StringField("efecto_4")
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_4(FlaskForm):
    objetivo_analisis = StringField("Objetivo Analisis", validators=[Required("Tienes que introducir el dato")])
    fecha = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    causa_raices = StringField("Causa Raices", validators=[Required("Tienes que introducir el dato")])
    plan_accion = StringField("Plan Accion", validators=[Required("Tienes que introducir el dato")])
    responsable = StringField("Responsable", validators=[Required("Tienes que introducir el dato")])
    fecha_1 = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    status = StringField("Status", validators=[Required("Tienes que introducir el dato")])
    explique = TextAreaField("Explique:", validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_4_efecto(FlaskForm):
    efecto_1 = StringField("efecto_1", validators=[Required("Tienes que introducir el dato")])
    efecto_2 = StringField("efecto_2", validators=[Required("Tienes que introducir el dato")])
    efecto_3 = StringField("efecto_3", validators=[Required("Tienes que introducir el dato")])
    efecto_4 = StringField("efecto_4")
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_5(FlaskForm):
    objetivo_analisis = StringField("Objetivo Analisis", validators=[Required("Tienes que introducir el dato")])
    fecha = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    causa_raices = StringField("Causa Raices", validators=[Required("Tienes que introducir el dato")])
    plan_accion = StringField("Plan Accion", validators=[Required("Tienes que introducir el dato")])
    responsable = StringField("Responsable", validators=[Required("Tienes que introducir el dato")])
    fecha_1 = StringField("Fecha", validators=[Required("Tienes que introducir el dato")])
    status = StringField("Status", validators=[Required("Tienes que introducir el dato")])
    explique = TextAreaField("Explique:", validators=[Required("Tienes que introducir el dato")])
    enviar = SubmitField('Enviar')

class FormGapanalisis_fi_5_efecto(FlaskForm):
    efecto_1 = StringField("efecto_1", validators=[Required("Tienes que introducir el dato")])
    efecto_2 = StringField("efecto_2", validators=[Required("Tienes que introducir el dato")])
    efecto_3 = StringField("efecto_3", validators=[Required("Tienes que introducir el dato")])
    efecto_4 = StringField("efecto_4")
    enviar = SubmitField('Enviar')