from sqlalchemy import Boolean, Column, ForeignKey
from sqlalchemy import DateTime, Integer, String, Text, Float
from sqlalchemy.sql import func 
from sqlalchemy.orm import relationship, backref
from aplicacion.app import db
from werkzeug.security import generate_password_hash, check_password_hash

class Reverso_bosch_1(db.Model):
    """Reverso Cto Slab 1s Bosch"""
    __tablename__ = 'cto_reverso_slab_1s_bosch_1'
    id = Column(Integer, primary_key=True)
    verifica_area_limpia = Column(String(100))
    verifica_tools_limpias = Column(String(100))
    verifica_cuchillas_de_corte = Column(String(100))
    verifica_canal_tableta = Column(String(100))
    verifica_cadena_tableta = Column(String(100))
    verifica_poleas_limpias = Column(String(100))
    verifica_discos_limpios = Column(String(100))
    verifica_cuchillas_goma = Column(String(100))
    verifica_poleas_estado = Column(String(100))
    verifica_interior_libre_metal = Column(String(100))
    verifica_discos_estado = Column(String(100))
    verifica_mordazas_limpias = Column(String(100))
    primera_hora = Column(String(100))
    segunda_hora = Column(String(100))
    tercera_hora = Column(String(100))
    cuarta_hora = Column(String(100))
    quinta_hora = Column(String(100))
    sexta_hora = Column(String(100))
    septima_hora = Column(String(100))
    octava_hora = Column(String(100))
    novena_hora = Column(String(100))
    temperatura_de_mordazas = Column(String(100))
    temperatura_de_sellado = Column(String(100))
    limpieza_bosch = Column(String(100))
    limpieza_emp_manual = Column(String(100))
    ancho_de_tira = Column(String(100))
    espesor_de_tira = Column(String(100))
    tira_sin_grumos = Column(String(100))
    tira_sin_manchas = Column(String(100))
    min_paros_planeados = Column(String(100))
    min_paros_no_planeados = Column(String(100))
    num_paros_menores = Column(String(100))
    ge = Column(String(100))
    vel_banda_2_transporte = Column(String(100))
    vel_banda_4_transporte = Column(String(100))
    altura_de_tira_sis_relajacion = Column(String(100))
    apertura_polea_1 = Column(String(100))
    apertura_polea_2 = Column(String(100))
    apertura_polea_3 = Column(String(100))
    dosificador_de_talco = Column(String(100))
    t_de_espera_dosificador = Column(String(100))
    t_de_act_en_dosificador = Column(String(100))
    corte_long_tableta = Column(String(100))
    long_de_etiquetado = Column(String(100))
    posicion_del_cursor = Column(String(100))
    posicion_del_prod_bobina = Column(String(100))
    posicion_de_impresion = Column(String(100))
    vel_banda_6 = Column(String(100))
    sobre_incompleto_inicio = Column(String(100))
    sobre_incompleto_medio = Column(String(100))
    sobre_incompleto_fin = Column(String(100))
    mal_sellado_inicio = Column(String(100))
    mal_sellado_medio = Column(String(100))
    mal_sellado_fin = Column(String(100))
    sobre_mordido_inicio = Column(String(100))
    sobre_mordido_medio = Column(String(100))
    sobre_mordido_fin = Column(String(100))
    sobre_descentrado_inicio = Column(String(100))
    sobre_descentrado_medio = Column(String(100))
    sobre_descentrado_fin = Column(String(100))
    sobre_con_impresion_defectuosa_inicio = Column(String(100))
    sobre_con_impresion_defectuosa_medio = Column(String(100))
    sobre_con_impresion_defectuosa_final = Column(String(100))
    tableta_deforme_inicio = Column(String(100))
    tableta_deforme_medio = Column(String(100))
    tableta_deforme_fin = Column(String(100))
    sobre_mal_codificado_inicio = Column(String(100))
    sobre_mal_codificado_medio = Column(String(100))
    sobre_mal_codificado_fin = Column(String(100))

    def __repr__(self):
        return (u'<{self.__class__.__name__}: {self.id}>'.format(self=self))

class Reverso_bosch_2(db.Model):
    """Reverso Cto Slab 1s Bosch 2"""
    __tablename__ = 'cto_reverso_slab_1s_bosch_2'
    id = Column(Integer, primary_key=True)
    verifica_area_limpia = Column(String(100))
    verifica_tools_limpias = Column(String(100))
    verifica_cuchillas_de_corte = Column(String(100))
    verifica_canal_tableta = Column(String(100))
    verifica_cadena_tableta = Column(String(100))
    verifica_poleas_limpias = Column(String(100))
    verifica_discos_limpios = Column(String(100))
    verifica_cuchillas_goma = Column(String(100))
    verifica_poleas_estado = Column(String(100))
    verifica_interior_libre_metal = Column(String(100))
    verifica_discos_estado = Column(String(100))
    verifica_mordazas_limpias = Column(String(100))
    primera_hora = Column(String(100))
    segunda_hora = Column(String(100))
    tercera_hora = Column(String(100))
    cuarta_hora = Column(String(100))
    quinta_hora = Column(String(100))
    sexta_hora = Column(String(100))
    septima_hora = Column(String(100))
    octava_hora = Column(String(100))
    novena_hora = Column(String(100))
    temperatura_de_mordazas = Column(String(100))
    temperatura_de_sellado = Column(String(100))
    limpieza_bosch = Column(String(100))
    limpieza_emp_manual = Column(String(100))
    ancho_de_tira = Column(String(100))
    espesor_de_tira = Column(String(100))
    tira_sin_grumos = Column(String(100))
    tira_sin_manchas = Column(String(100))
    min_paros_planeados = Column(String(100))
    min_paros_no_planeados = Column(String(100))
    num_paros_menores = Column(String(100))
    ge = Column(String(100))
    vel_banda_2_transporte = Column(String(100))
    vel_banda_4_transporte = Column(String(100))
    altura_de_tira_sis_relajacion = Column(String(100))
    apertura_polea_1 = Column(String(100))
    apertura_polea_2 = Column(String(100))
    apertura_polea_3 = Column(String(100))
    dosificador_de_talco = Column(String(100))
    t_de_espera_dosificador = Column(String(100))
    t_de_act_en_dosificador = Column(String(100))
    corte_long_tableta = Column(String(100))
    long_de_etiquetado = Column(String(100))
    posicion_del_cursor = Column(String(100))
    posicion_del_prod_bobina = Column(String(100))
    posicion_de_impresion = Column(String(100))
    vel_banda_6 = Column(String(100))
    sobre_incompleto_inicio = Column(String(100))
    sobre_incompleto_medio = Column(String(100))
    sobre_incompleto_fin = Column(String(100))
    mal_sellado_inicio = Column(String(100))
    mal_sellado_medio = Column(String(100))
    mal_sellado_fin = Column(String(100))
    sobre_mordido_inicio = Column(String(100))
    sobre_mordido_medio = Column(String(100))
    sobre_mordido_fin = Column(String(100))
    sobre_descentrado_inicio = Column(String(100))
    sobre_descentrado_medio = Column(String(100))
    sobre_descentrado_fin = Column(String(100))
    sobre_con_impresion_defectuosa_inicio = Column(String(100))
    sobre_con_impresion_defectuosa_medio = Column(String(100))
    sobre_con_impresion_defectuosa_final = Column(String(100))
    tableta_deforme_inicio = Column(String(100))
    tableta_deforme_medio = Column(String(100))
    tableta_deforme_fin = Column(String(100))
    sobre_mal_codificado_inicio = Column(String(100))
    sobre_mal_codificado_medio = Column(String(100))
    sobre_mal_codificado_fin = Column(String(100))

    def __repr__(self):
        return (u'<{self.__class__.__name__}: {self.id}>'.format(self=self))
